class PresenceService:
    def get_present_devices(self) -> list[Device]: ...
    def get_present_authorized_devices(self) -> list[Device]: ...
    def get_present_pending_devices(self) -> list[Device]: ...
    def get_present_blocked_devices(self) -> list[Device]: ...
    def is_approved_user_present(self) -> bool: ...