"""
Central configuration for Signally.

This file keeps all tunable values in one place so the system can later move
from local demo mode to Raspberry Pi + real CSI + real frontend integration
without changing business logic code.
"""

from __future__ import annotations

import os


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Database
DATABASE_URL = os.getenv("SIGNALLY_DATABASE_URL", "sqlite:///signally.db")

# Auth / JWT
JWT_SECRET = os.getenv("SIGNALLY_JWT_SECRET", "dev-secret-change-in-production")
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_HOURS = int(os.getenv("SIGNALLY_JWT_EXPIRE_HOURS", "168"))  # 7 days

#  ARP scanning
DEFAULT_SCAN_TARGET = os.getenv("SIGNALLY_DEFAULT_SCAN_TARGET", "192.168.1.0/24")
DEFAULT_SCAN_TIMEOUT = int(os.getenv("SIGNALLY_DEFAULT_SCAN_TIMEOUT", "2"))

# Presence logic
# A device is considered "currently present" if it was seen in the last X seconds.
PRESENCE_WINDOW_SECONDS = int(os.getenv("SIGNALLY_PRESENCE_WINDOW_SECONDS", "30"))
CURRENT_UNKNOWN_WINDOW_SECONDS = int(os.getenv("SIGNALLY_CURRENT_UNKNOWN_WINDOW_SECONDS", "30"))
ADMIN_REVIEW_GRACE_SECONDS = int(os.getenv("SIGNALLY_ADMIN_REVIEW_GRACE_SECONDS", "30"))

# Monitoring loop
MONITOR_INTERVAL_SECONDS = int(os.getenv("SIGNALLY_MONITOR_INTERVAL_SECONDS", "10"))
AUTO_START_MONITORING = _env_bool("SIGNALLY_AUTO_START_MONITORING", True)
ALERT_COOLDOWN_SECONDS = int(os.getenv("SIGNALLY_ALERT_COOLDOWN_SECONDS", "60"))

# Guest approval window
GUEST_APPROVAL_HOURS = int(os.getenv("SIGNALLY_GUEST_APPROVAL_HOURS", "24"))

# WIFI probing 
UNASSOCIATED_IP_ADDRESS = os.getenv("SIGNALLY_UNASSOCIATED_IP_ADDRESS", "UNASSOCIATED")
AUTO_START_WIFI_PROBING = _env_bool("SIGNALLY_AUTO_START_WIFI_PROBING", True)
WIFI_PROBING_INTERFACE = os.getenv("SIGNALLY_WIFI_PROBING_INTERFACE", "wlan1")
WIFI_PROBING_MOCK_MODE = _env_bool("SIGNALLY_WIFI_PROBING_MOCK_MODE", False)
WIFI_PROBING_FALLBACK_TO_MOCK = _env_bool("SIGNALLY_WIFI_PROBING_FALLBACK_TO_MOCK", True)

# CSI / Nexmon sensing. Nexmon itself is an external Raspberry Pi dependency.
CSI_REAL_PROVIDER_ENABLED = _env_bool("SIGNALLY_CSI_REAL_PROVIDER_ENABLED", False)
CSI_UDP_HOST = os.getenv("SIGNALLY_CSI_UDP_HOST", "0.0.0.0")
CSI_UDP_PORT = int(os.getenv("SIGNALLY_CSI_UDP_PORT", "5500"))
CSI_PACKET_BUFFER_SIZE = int(os.getenv("SIGNALLY_CSI_PACKET_BUFFER_SIZE", "500"))
CSI_PACKET_STALE_AFTER_SECONDS = float(os.getenv("SIGNALLY_CSI_PACKET_STALE_AFTER_SECONDS", "3.0"))
CSI_FEATURE_WINDOW_SECONDS = float(os.getenv("SIGNALLY_CSI_FEATURE_WINDOW_SECONDS", "3.0"))
CSI_BASELINE_MIN_PACKETS = int(os.getenv("SIGNALLY_CSI_BASELINE_MIN_PACKETS", "5"))
CSI_BASELINE_THRESHOLD_MULTIPLIER = float(
    os.getenv("SIGNALLY_CSI_BASELINE_THRESHOLD_MULTIPLIER", "3.0")
)
CSI_BASELINE_MIN_THRESHOLD = float(os.getenv("SIGNALLY_CSI_BASELINE_MIN_THRESHOLD", "5.0"))

EVENT_DEVICE_DELETED = "DEVICE_DELETED"
EVENT_GUEST_APPROVAL_EXPIRED = "GUEST_APPROVAL_EXPIRED"
EVENT_SECURITY_MODE_CHANGED = "SECURITY_MODE_CHANGED"

EVENT_WIFI_PROBING_STARTED = "WIFI_PROBING_STARTED"
EVENT_WIFI_PROBING_STOPPED = "WIFI_PROBING_STOPPED"
EVENT_WIFI_PROBING_ERROR = "WIFI_PROBING_ERROR"
EVENT_WIFI_PROBE_NEARBY_ACTIVITY = "WIFI_PROBE_NEARBY_ACTIVITY"

WIFI_PROBING_RECENT_EVENT_LIMIT = int(
    os.getenv("SIGNALLY_WIFI_PROBING_RECENT_EVENT_LIMIT", "500")
)

WIFI_PROBING_STRONG_RSSI_MIN = int(
    os.getenv("SIGNALLY_WIFI_PROBING_STRONG_RSSI_MIN", "-60")
)



# Event types
EVENT_DEVICE_DISCOVERED_NEW = "DEVICE_DISCOVERED_NEW"
EVENT_DEVICE_SEEN_AGAIN = "DEVICE_SEEN_AGAIN"
EVENT_DEVICE_APPROVED = "DEVICE_APPROVED"
EVENT_DEVICE_BLOCKED = "DEVICE_BLOCKED"

EVENT_APPROVED_USER_PRESENT = "APPROVED_USER_PRESENT"
EVENT_NO_APPROVED_USER_PRESENT = "NO_APPROVED_USER_PRESENT"
EVENT_UNAUTHORIZED_PRESENCE_ALERT = "UNAUTHORIZED_PRESENCE_ALERT"
EVENT_BLOCKED_DEVICE_ALERT = "BLOCKED_DEVICE_ALERT"
EVENT_MONITORING_CYCLE_COMPLETED = "MONITORING_CYCLE_COMPLETED"
