"""
Central configuration for Signally.

This file keeps all tunable values in one place so the system can later move
from local demo mode to Raspberry Pi + real CSI + real frontend integration
without changing business logic code.
"""

from __future__ import annotations

import os


# Database
DATABASE_URL = os.getenv("SIGNALLY_DATABASE_URL", "sqlite:///signally.db")

# Auth / JWT
JWT_SECRET = os.getenv("SIGNALLY_JWT_SECRET", "dev-secret-change-in-production")
JWT_ALGORITHM = "HS256"
JWT_EXPIRE_HOURS = int(os.getenv("SIGNALLY_JWT_EXPIRE_HOURS", "168"))  # 7 days

#  ARP scanning
DEFAULT_SCAN_TARGET = os.getenv("SIGNALLY_DEFAULT_SCAN_TARGET", "192.168.1.0/24")
DEFAULT_SCAN_TIMEOUT = int(os.getenv("SIGNALLY_DEFAULT_SCAN_TIMEOUT", "2"))

# Presence logic
# A device is considered "currently present" if it was seen in the last X seconds.
PRESENCE_WINDOW_SECONDS = int(os.getenv("SIGNALLY_PRESENCE_WINDOW_SECONDS", "30"))
CURRENT_UNKNOWN_WINDOW_SECONDS = int(os.getenv("SIGNALLY_CURRENT_UNKNOWN_WINDOW_SECONDS", "30"))
ADMIN_REVIEW_GRACE_SECONDS = int(os.getenv("SIGNALLY_ADMIN_REVIEW_GRACE_SECONDS", "30"))

# Monitoring loop
MONITOR_INTERVAL_SECONDS = int(os.getenv("SIGNALLY_MONITOR_INTERVAL_SECONDS", "10"))
ALERT_EVENT_COOLDOWN_SECONDS = int(os.getenv("SIGNALLY_ALERT_EVENT_COOLDOWN_SECONDS", "60"))

# Guest approval window
GUEST_APPROVAL_HOURS = int(os.getenv("SIGNALLY_GUEST_APPROVAL_HOURS", "24"))

# WIFI probing 
UNASSOCIATED_IP_ADDRESS = os.getenv("SIGNALLY_UNASSOCIATED_IP_ADDRESS", "UNASSOCIATED")
WIFI_PROBING_AUTO_MATCH_CHANNEL = (
    os.getenv("SIGNALLY_WIFI_PROBING_AUTO_MATCH_CHANNEL", "true").lower()
    in ("1", "true", "yes", "on")
)
WIFI_PROBING_FOLLOW_INTERFACE = os.getenv("SIGNALLY_WIFI_PROBING_FOLLOW_INTERFACE", "wlan0")

EVENT_DEVICE_DELETED = "DEVICE_DELETED"
EVENT_GUEST_APPROVAL_EXPIRED = "GUEST_APPROVAL_EXPIRED"
EVENT_SECURITY_MODE_CHANGED = "SECURITY_MODE_CHANGED"

EVENT_WIFI_PROBING_STARTED = "WIFI_PROBING_STARTED"
EVENT_WIFI_PROBING_STOPPED = "WIFI_PROBING_STOPPED"
EVENT_WIFI_PROBING_ERROR = "WIFI_PROBING_ERROR"
EVENT_WIFI_PROBE_NEARBY_ACTIVITY = "WIFI_PROBE_NEARBY_ACTIVITY"

WIFI_PROBING_RECENT_EVENT_LIMIT = int(
    os.getenv("SIGNALLY_WIFI_PROBING_RECENT_EVENT_LIMIT", "500")
)

WIFI_PROBE_ACTIVITY_COOLDOWN_SECONDS = int(
    os.getenv("SIGNALLY_WIFI_PROBE_ACTIVITY_COOLDOWN_SECONDS", str(CURRENT_UNKNOWN_WINDOW_SECONDS))
)

WIFI_PROBING_STRONG_RSSI_MIN = int(
    os.getenv("SIGNALLY_WIFI_PROBING_STRONG_RSSI_MIN", "-60")
)

WIFI_PROBING_ALLOW_MISSING_RSSI = (
    os.getenv("SIGNALLY_WIFI_PROBING_ALLOW_MISSING_RSSI", "true").lower()
    in ("1", "true", "yes", "on")
)



# Event types
EVENT_DEVICE_DISCOVERED_NEW = "DEVICE_DISCOVERED_NEW"
EVENT_DEVICE_SEEN_AGAIN = "DEVICE_SEEN_AGAIN"
EVENT_DEVICE_APPROVED = "DEVICE_APPROVED"
EVENT_DEVICE_BLOCKED = "DEVICE_BLOCKED"

EVENT_APPROVED_USER_PRESENT = "APPROVED_USER_PRESENT"
EVENT_NO_APPROVED_USER_PRESENT = "NO_APPROVED_USER_PRESENT"
EVENT_UNAUTHORIZED_PRESENCE_ALERT = "UNAUTHORIZED_PRESENCE_ALERT"
EVENT_BLOCKED_DEVICE_ALERT = "BLOCKED_DEVICE_ALERT"
EVENT_MONITORING_CYCLE_COMPLETED = "MONITORING_CYCLE_COMPLETED"
